<Downloader>:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            Label:
                text: "Animes"
            Button:
                text: "Baixar"
                on_release: 
                    app.root.current = 'animes'
        BoxLayout:
            Label:
                text: "Mangás"
            Button:
                text: "Baixar"
                on_release:
                    app.root.current = 'mangas'

